### ISSUE TITLE
Add validateInstance() to KernelInstance registration logic

### ISSUE THREAD

**Issue by martriay** [zeppelinos/kernel#15]
The current `ZepCore` implementation allows any `KernelInstance` to be registered as long as the sender had set the due ZepToken allowance and there isn't a name/version clash in the registry.

Considering that:

1. Although our current staking model encourages forking from a high-staked distribution version to attract its "audience", the base kernel needs to be frozen to be a fork's parent and that's up to the base kernel developer. This way, the developer can "deny" other developers forking from it.
2. Stakers today can stake for an unfrozen (mutable) distribution version. This allows the developer to add new implementations after staking.
3. I can register a `KernelInstance` whose parent is not in the registry.

I think we should include a `validateInstance()` function (or modifier) to ZepCore's `register()` to perform all the necessary checks before registering a `KernelInstance`.

To start, I'd enforce that an instance has to be frozen and its parent registered, matching not only its name/version hash but its address too.

Thoughts?

**Comment by frangio** [comment]
Resolved since releases have to be frozen to be registered, and they no longer have parents.
