### ISSUE TITLE
Check pricing of registration and payouts in ZepCore

### ISSUE THREAD

**Issue by fiiiu** [zeppelinos/kernel#7]
Right now, the `_newVersionCost` variable specifying the cost of deploying a new kernel version, and `_developerFraction`, which specifies the fraction of each vouch that is forwarded to the version developer, are fixed by `ZepCore`'s constructor. The only way to modify them is to go through a full kernel upgrade.

We should evaluate the possibility of introducing a mechanism to change these without resorting to an upgrade (maybe a simple setter would do?).

**Comment by maraoz** [comment]
.@frangio and I just checked that the current implementation is in accord with what is described in the [zOS whitepaper](https://zeppelinos.org/zeppelin_os_whitepaper.pdf). We should update the whitepaper to mention that:
- register cost is fixed and the tokens are burnt (whitepaper currently doesn't specify where those tokens go)
- payout to developers use a linear function of the tokens vouched. 

Further analysis of the dynamics will be performed in the external security audit https://github.com/zeppelinos/labs/issues/89.
